const KEY="cliquefacil_clients";
const templates=[
{id:"pizzaria",icon:"🍕",name:"Pizzaria / Restaurante",desc:"Cardápio, pedidos e informações do estabelecimento."},
{id:"barbearia",icon:"💈",name:"Barbearia",desc:"Serviços, profissionais e agendamento."},
{id:"salao",icon:"💇",name:"Salão de beleza",desc:"Serviços, profissionais e horários."},
{id:"estetica",icon:"💅",name:"Estética / Manicure",desc:"Catálogo de serviços e agenda."},
{id:"loja",icon:"🛍️",name:"Loja",desc:"Produtos, contato, localização e pedidos."},
{id:"autonomo",icon:"🧑‍💼",name:"Profissional autônomo",desc:"Apresente seus serviços e facilite o contato."}
];
let clients=JSON.parse(localStorage.getItem(KEY)||"[]"),view="dashboard";
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const save=()=>localStorage.setItem(KEY,JSON.stringify(clients));
const tname=id=>templates.find(t=>t.id===id)?.name||"Serviço";

function shell(content){
document.querySelector("#app").innerHTML=`<div><header class="topbar"><div class="brand">Clique<span>Fácil</span></div><div class="top-actions"><button class="btn secondary" onclick="preview()">Visualizar site</button><button class="btn primary" onclick="newClient()">+ Nova página</button></div></header><div class="layout"><aside class="sidebar"><nav class="nav"><button class="${view==="dashboard"?"active":""}" onclick="dashboard()">📊 Visão geral</button><button class="${view==="clients"?"active":""}" onclick="clientsView()">👥 Clientes</button><button class="${view==="templates"?"active":""}" onclick="templatesView()">🧩 Modelos</button><button onclick="newClient()">➕ Criar página</button></nav></aside><main class="main">${content}</main></div></div>`;
}
function dashboard(){view="dashboard";shell(`<section class="hero"><div><h1>Visão geral</h1><div class="muted">Uma base para criar e gerenciar páginas de vários clientes.</div></div></section><section class="cards"><div class="card"><div class="muted">Clientes</div><div class="stat">${clients.length}</div></div><div class="card"><div class="muted">Páginas ativas</div><div class="stat">${clients.filter(c=>c.active).length}</div></div><div class="card"><div class="muted">Modelos</div><div class="stat">${templates.length}</div></div><div class="card"><div class="muted">Estrutura</div><div class="stat">Multi</div></div></section><div class="card"><h2>Comece criando uma página</h2><p class="muted">Escolha um segmento e personalize os dados do cliente.</p><button class="btn primary" onclick="newClient()">Criar página</button></div>`);}
function clientsView(){view="clients";const rows=clients.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${tname(c.template)}</td><td><span class="badge ${c.active?"on":"off"}">${c.active?"Ativa":"Inativa"}</span></td><td><button class="btn ghost" onclick="editClient('${c.id}')">Editar</button> <button class="btn secondary" onclick="publicPage('${c.id}')">Abrir</button></td></tr>`).join("");shell(`<section class="hero"><div><h1>Clientes</h1><div class="muted">Cada cliente possui seus próprios dados.</div></div><button class="btn primary" onclick="newClient()">+ Nova página</button></section>${clients.length?`<table class="table"><thead><tr><th>Cliente</th><th>Segmento</th><th>Status</th><th>Ações</th></tr></thead><tbody>${rows}</tbody></table>`:`<div class="card" style="text-align:center;padding:55px">Nenhum cliente cadastrado.</div>`}`);}
function templatesView(){view="templates";shell(`<section class="hero"><div><h1>Modelos</h1><div class="muted">Uma estrutura reutilizável para diferentes segmentos.</div></div></section><div class="grid">${templates.map(t=>`<article class="template"><div class="icon">${t.icon}</div><h3>${t.name}</h3><p>${t.desc}</p><button class="btn secondary" onclick="newClient('${t.id}')">Usar modelo</button></article>`).join("")}</div>`);}
function newClient(template="pizzaria"){view="form";formView({template});}
function editClient(id){const c=clients.find(x=>x.id===id);if(c){view="form";formView(c);}}
function formView(data={}){const c={name:"",description:"",phone:"",instagram:"",address:"",hours:"",accent:"#5b5cf0",template:data.template||"pizzaria",active:true,...data};shell(`<section class="hero"><div><h1>${data.id?"Editar página":"Nova página"}</h1><div class="muted">Configure os dados da página pública.</div></div></section><form class="form" onsubmit="submitClient(event,'${c.id||""}')"><div class="form-grid"><div class="field"><label>Nome da empresa</label><input name="name" required value="${esc(c.name)}" placeholder="Ex.: Pizzaria Oliveira"></div><div class="field"><label>Segmento</label><select name="template">${templates.map(t=>`<option value="${t.id}" ${c.template===t.id?"selected":""}>${t.icon} ${t.name}</option>`).join("")}</select></div><div class="field full"><label>Descrição</label><textarea name="description">${esc(c.description)}</textarea></div><div class="field"><label>WhatsApp</label><input name="phone" value="${esc(c.phone)}"></div><div class="field"><label>Instagram</label><input name="instagram" value="${esc(c.instagram)}"></div><div class="field full"><label>Endereço</label><input name="address" value="${esc(c.address)}"></div><div class="field"><label>Horário</label><input name="hours" value="${esc(c.hours)}"></div><div class="field"><label>Cor principal</label><input type="color" name="accent" value="${c.accent}"></div></div><div class="actions"><button type="button" class="btn ghost" onclick="clientsView()">Cancelar</button><button class="btn primary">Salvar página</button></div></form>`);}
function submitClient(e,id){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.active=true;if(id){const i=clients.findIndex(c=>c.id===id);clients[i]={...clients[i],...data};}else{data.id=crypto.randomUUID();data.createdAt=new Date().toISOString();clients.push(data);}save();clientsView();}
function publicPage(id){const c=clients.find(x=>x.id===id);if(c)renderPublic(c);}
function preview(){if(clients[0])renderPublic(clients[0]);else alert("Crie uma página primeiro.");}
function renderPublic(c){document.body.style.setProperty("--accent",c.accent||"#5b5cf0");document.querySelector("#app").innerHTML=`<div class="public"><header class="public-head"><button class="btn" onclick="dashboard()" style="background:#ffffff22;color:#fff">← Painel</button><div style="font-size:42px;margin-top:18px">⭐</div><h1>${esc(c.name)}</h1><p>${esc(c.description||"Bem-vindo!")}</p></header><main class="public-content"><div class="card"><h2>Informações</h2><p>📍 ${esc(c.address||"Endereço não informado")}</p><p>🕒 ${esc(c.hours||"Horário não informado")}</p><p>📱 ${esc(c.phone||"WhatsApp não informado")}</p><p>📸 ${esc(c.instagram||"Instagram não informado")}</p></div><div class="card" style="margin-top:16px"><h2>${c.template==="pizzaria"||c.template==="loja"?"Cardápio / Produtos":"Serviços"}</h2><div class="items"><div class="item"><strong>Item de exemplo</strong><span>R$ 0,00</span></div><div class="item"><strong>Outro item</strong><span>Consultar</span></div></div><button class="btn primary" style="margin-top:18px;width:100%">Entrar em contato / Agendar</button></div></main></div>`;}
dashboard();