const CLIENTS_KEY="cliquefacil_clients",ITEMS_KEY="cliquefacil_items";
const templates=[{id:"pizzaria",icon:"🍕",name:"Pizzaria / Restaurante",desc:"Cardápio, pedidos e informações."},{id:"barbearia",icon:"💈",name:"Barbearia",desc:"Serviços e agendamento."},{id:"salao",icon:"💇",name:"Salão de beleza",desc:"Serviços, profissionais e horários."},{id:"estetica",icon:"💅",name:"Estética / Manicure",desc:"Catálogo de serviços e agenda."},{id:"loja",icon:"🛍️",name:"Loja",desc:"Produtos, contato e pedidos."},{id:"autonomo",icon:"🧑‍💼",name:"Profissional autônomo",desc:"Serviços e contato."}];
let clients=JSON.parse(localStorage.getItem(CLIENTS_KEY)||"[]"),items=JSON.parse(localStorage.getItem(ITEMS_KEY)||"{}"),view="dashboard";
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const save=()=>{localStorage.setItem(CLIENTS_KEY,JSON.stringify(clients));localStorage.setItem(ITEMS_KEY,JSON.stringify(items));};
const tname=id=>templates.find(t=>t.id===id)?.name||"Serviço",clientItems=id=>items[id]||[];
const slugify=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,60);
const uniqueSlug=(name,id)=>{let b=slugify(name)||"pagina",s=b,n=2;while(clients.some(c=>c.slug===s&&c.id!==id))s=b+"-"+n++;return s;};
const publicUrl=c=>location.href.split("?")[0]+"?site="+encodeURIComponent(c.slug);
function shell(content){document.querySelector("#app").innerHTML=`<header class="topbar"><div class="brand">Clique<span>Fácil</span></div><div class="top-actions"><button class="btn secondary" onclick="preview()">Visualizar site</button><button class="btn primary" onclick="newClient()">+ Nova página</button></div></header><div class="layout"><aside class="sidebar"><nav class="nav"><button class="${view==="dashboard"?"active":""}" onclick="dashboard()">📊 Visão geral</button><button class="${view==="clients"?"active":""}" onclick="clientsView()">👥 Clientes</button><button class="${view==="templates"?"active":""}" onclick="templatesView()">🧩 Modelos</button><button onclick="newClient()">➕ Criar página</button></nav></aside><main class="main">${content}</main></div>`;}
function dashboard(){view="dashboard";shell(`<section class="hero"><div><h1>Visão geral</h1><div class="muted">Gerencie páginas independentes para vários clientes.</div></div></section><section class="cards"><div class="card"><div class="muted">Clientes</div><div class="stat">${clients.length}</div></div><div class="card"><div class="muted">Páginas ativas</div><div class="stat">${clients.filter(c=>c.active).length}</div></div><div class="card"><div class="muted">Modelos</div><div class="stat">${templates.length}</div></div><div class="card"><div class="muted">Itens cadastrados</div><div class="stat">${Object.values(items).reduce((n,a)=>n+a.length,0)}</div></div></section><div class="card"><h2>Próximo passo</h2><p class="muted">Crie uma página, cadastre produtos/serviços e abra o link individual do cliente.</p><button class="btn primary" onclick="newClient()">Criar página</button></div>`);}
function clientsView(){view="clients";const rows=clients.map(c=>`<tr><td><strong>${esc(c.name)}</strong><div class="small-muted">/${esc(c.slug||"")}</div></td><td>${tname(c.template)}</td><td><span class="badge ${c.active?"on":"off"}">${c.active?"Ativa":"Inativa"}</span></td><td>${clientItems(c.id).length}</td><td><button class="btn ghost" onclick="editClient('${c.id}')">Editar</button> <button class="btn secondary" onclick="manageItems('${c.id}')">Catálogo</button> <button class="btn primary" onclick="publicPage('${c.id}')">Abrir</button></td></tr>`).join("");shell(`<section class="hero"><div><h1>Clientes</h1><div class="muted">Cada cliente possui página, slug e catálogo próprios.</div></div><button class="btn primary" onclick="newClient()">+ Nova página</button></section>${clients.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Cliente</th><th>Segmento</th><th>Status</th><th>Itens</th><th>Ações</th></tr></thead><tbody>${rows}</tbody></table></div>`:`<div class="card empty">Nenhum cliente cadastrado.</div>`}`);}
function templatesView(){view="templates";shell(`<section class="hero"><div><h1>Modelos</h1><div class="muted">Estruturas reutilizáveis por segmento.</div></div></section><div class="grid">${templates.map(t=>`<article class="template"><div class="icon">${t.icon}</div><h3>${t.name}</h3><p>${t.desc}</p><button class="btn secondary" onclick="newClient('${t.id}')">Usar modelo</button></article>`).join("")}</div>`);}
function newClient(template="pizzaria"){view="form";formView({template});}
function editClient(id){const c=clients.find(x=>x.id===id);if(c){view="form";formView(c);}}
function formView(data={}){const c={name:"",description:"",phone:"",instagram:"",address:"",hours:"",accent:"#5b5cf0",template:data.template||"pizzaria",active:true,...data};shell(`<section class="hero"><div><h1>${data.id?"Editar página":"Nova página"}</h1><div class="muted">Configure os dados da página pública.</div></div></section><form class="form" onsubmit="submitClient(event,'${c.id||""}')"><div class="form-grid"><div class="field"><label>Nome da empresa</label><input name="name" required value="${esc(c.name)}" placeholder="Ex.: Pizzaria Oliveira"></div><div class="field"><label>Segmento</label><select name="template">${templates.map(t=>`<option value="${t.id}" ${c.template===t.id?"selected":""}>${t.icon} ${t.name}</option>`).join("")}</select></div><div class="field full"><label>Descrição</label><textarea name="description">${esc(c.description)}</textarea></div><div class="field"><label>WhatsApp</label><input name="phone" value="${esc(c.phone)}" placeholder="5512991119914"></div><div class="field"><label>Instagram</label><input name="instagram" value="${esc(c.instagram)}" placeholder="@empresa"></div><div class="field full"><label>Endereço</label><input name="address" value="${esc(c.address)}"></div><div class="field"><label>Horário</label><input name="hours" value="${esc(c.hours)}"></div><div class="field"><label>Cor principal</label><input type="color" name="accent" value="${c.accent}"></div></div><div class="actions"><button type="button" class="btn ghost" onclick="clientsView()">Cancelar</button><button class="btn primary">Salvar página</button></div></form>`);}
function submitClient(e,id){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.active=true;data.slug=uniqueSlug(data.name,id);if(id){const i=clients.findIndex(c=>c.id===id);clients[i]={...clients[i],...data,updatedAt:new Date().toISOString()};}else{data.id=crypto.randomUUID();data.createdAt=new Date().toISOString();clients.push(data);items[data.id]=[];}save();clientsView();}
function manageItems(id){const c=clients.find(x=>x.id===id);if(!c)return;view="items";const list=clientItems(id);shell(`<section class="hero"><div><h1>Catálogo — ${esc(c.name)}</h1><div class="muted">${list.length} item(ns) • /${esc(c.slug)}</div></div><div><button class="btn ghost" onclick="clientsView()">Voltar</button> <button class="btn primary" onclick="itemForm('${id}')">+ Adicionar item</button></div></section>${list.length?`<div class="items-admin">${list.map(x=>`<article class="item-admin"><div><strong>${esc(x.name)}</strong><p>${esc(x.description||"")}</p><span class="price">${x.price?"R$ "+esc(x.price):"Preço sob consulta"}</span></div><div><button class="btn ghost" onclick="itemForm('${id}','${x.id}')">Editar</button> <button class="btn danger" onclick="deleteItem('${id}','${x.id}')">Excluir</button></div></article>`).join("")}</div>`:`<div class="card empty"><h3>Catálogo vazio</h3><p class="muted">Adicione o primeiro produto ou serviço.</p><button class="btn primary" onclick="itemForm('${id}')">Adicionar item</button></div>`}`);}
function itemForm(clientId,itemId){const old=clientItems(clientId).find(x=>x.id===itemId)||{name:"",description:"",price:"",category:"",active:true};const c=clients.find(x=>x.id===clientId);shell(`<section class="hero"><div><h1>${itemId?"Editar item":"Novo item"}</h1><div class="muted">Catálogo de ${esc(c?.name||"cliente")}</div></div></section><form class="form" onsubmit="submitItem(event,'${clientId}','${itemId||""}')"><div class="form-grid"><div class="field"><label>Nome</label><input name="name" required value="${esc(old.name)}" placeholder="Ex.: Pizza Calabresa"></div><div class="field"><label>Preço</label><input name="price" value="${esc(old.price)}" placeholder="39,90"></div><div class="field"><label>Categoria</label><input name="category" value="${esc(old.category)}" placeholder="Pizzas"></div><div class="field full"><label>Descrição</label><textarea name="description">${esc(old.description)}</textarea></div></div><div class="actions"><button type="button" class="btn ghost" onclick="manageItems('${clientId}')">Cancelar</button><button class="btn primary">Salvar item</button></div></form>`);}
function submitItem(e,clientId,itemId){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.active=true;const list=clientItems(clientId);if(itemId){const i=list.findIndex(x=>x.id===itemId);list[i]={...list[i],...data};}else list.push({id:crypto.randomUUID(),...data,createdAt:new Date().toISOString()});items[clientId]=list;save();manageItems(clientId);}
function deleteItem(clientId,itemId){if(!confirm("Excluir este item?"))return;items[clientId]=clientItems(clientId).filter(x=>x.id!==itemId);save();manageItems(clientId);}
function publicPage(id){const c=clients.find(x=>x.id===id);if(c)renderPublic(c);}
function preview(){if(clients[0])renderPublic(clients[0]);else alert("Crie uma página primeiro.");}
function renderPublic(c){document.body.style.setProperty("--accent",c.accent||"#5b5cf0");const list=clientItems(c.id).filter(x=>x.active),wa=String(c.phone||"").replace(/\D/g,"");const content=list.length?list.map(x=>`<div class="item"><div><strong>${esc(x.name)}</strong>${x.description?`<small>${esc(x.description)}</small>`:""}</div><span>${x.price?"R$ "+esc(x.price):"Consultar"}</span></div>`).join(""):`<div class="empty-inline">Nenhum item cadastrado ainda.</div>`;document.querySelector("#app").innerHTML=`<div class="public"><header class="public-head"><button class="btn public-back" onclick="dashboard()">← Painel</button><div class="public-icon">${templates.find(t=>t.id===c.template)?.icon||"⭐"}</div><h1>${esc(c.name)}</h1><p>${esc(c.description||"Bem-vindo!")}</p></header><main class="public-content"><div class="card"><h2>Informações</h2><p>📍 ${esc(c.address||"Endereço não informado")}</p><p>🕒 ${esc(c.hours||"Horário não informado")}</p>${c.phone?`<p>📱 ${esc(c.phone)}</p>`:""}${c.instagram?`<p>📸 ${esc(c.instagram)}</p>`:""}</div><div class="card" style="margin-top:16px"><h2>${c.template==="pizzaria"||c.template==="loja"?"Cardápio / Produtos":"Serviços"}</h2><div class="items">${content}</div>${wa?`<a class="btn primary public-cta" href="https://wa.me/${wa}" target="_blank" rel="noopener">Falar no WhatsApp</a>`:""}</div><div class="public-link"><span>Link desta página</span><code>?site=${esc(c.slug)}</code><button class="btn ghost" onclick="copyLink('${c.id}')">Copiar</button></div></main></div>`;}
function copyLink(id){const c=clients.find(x=>x.id===id);if(c&&navigator.clipboard)navigator.clipboard.writeText(publicUrl(c)).then(()=>alert("Link copiado!"));}
function openRequestedSite(){const slug=new URLSearchParams(location.search).get("site");if(!slug)return false;const c=clients.find(x=>x.slug===slug);if(c&&c.active){renderPublic(c);return true;}return false;}
if(!openRequestedSite())dashboard();